### ISSUE TITLE
Image (enclosure) is used for "Learn more" hyperlink instead of item URL

### ISSUE THREAD

**Issue by Guts** [qgis/QGIS-Planet-Website#31]
On this page https://qgis.github.io/QGIS-Planet-Website/subscribers/geotribu_en/ the "Learn more" points to the item's image (enclosure).

The source RSS looks clean:

```xml
<item>
<title>Track the Vendée Globe race with Python and QGIS</title>
<author>ffougeres</author>
<category>Article</category>
<category>GeoPandas</category>
<category>Pandas</category>
<category>Python</category>
<category>QGIS</category>
<category>Vendée Globe</category>
<category>sailing</category>
<description>
Create and visualize GIS data on the progress of the Vendée Globe 2024 race from official spreadsheets.
</description>
<link>
https://blog.geotribu.net/2024/12/02/track-the-vend%C3%A9e-globe-race-with-python-and-qgis/?utm_source=rss-feed&utm_medium=RSS&utm_campaign=feed-syndication
</link>
<pubDate>Mon, 02 Dec 2024 09:09:00 +0000</pubDate>
<source url="https://blog.geotribu.net/feed_rss_created.xml">Geotribu in English</source>
<comments>
https://blog.geotribu.net/2024/12/02/track-the-vend%C3%A9e-globe-race-with-python-and-qgis/#__comments
</comments>
<guid isPermaLink="true">
https://blog.geotribu.net/2024/12/02/track-the-vend%C3%A9e-globe-race-with-python-and-qgis/
</guid>
<enclosure url="https://blog.geotribu.net/assets/images/social/2024/12/02/track-the-vendée-globe-race-with-python-and-qgis.png" type="image/png" length="65577"/>
</item>
<item>
<title>
Creating a Python virtual environment for PyQGIS development with VS Code on Windows
</title>
<author>nicogodet</author>
<category>Plugin QGIS</category>
<category>PyQGIS</category>
<category>Python</category>
<category>Tutorial</category>
<category>VS Code</category>
<category>Windows</category>
<description>For Intellisense happiness</description>
<link>
https://blog.geotribu.net/2024/11/25/creating-a-python-virtual-environment-for-pyqgis-development-with-vs-code-on-windows/?utm_source=rss-feed&utm_medium=RSS&utm_campaign=feed-syndication
</link>
<pubDate>Mon, 25 Nov 2024 09:09:00 +0000</pubDate>
<source url="https://blog.geotribu.net/feed_rss_created.xml">Geotribu in English</source>
<comments>
https://blog.geotribu.net/2024/11/25/creating-a-python-virtual-environment-for-pyqgis-development-with-vs-code-on-windows/#__comments
</comments>
<guid isPermaLink="true">
https://blog.geotribu.net/2024/11/25/creating-a-python-virtual-environment-for-pyqgis-development-with-vs-code-on-windows/
</guid>
<enclosure url="https://blog.geotribu.net/assets/images/social/2024/11/25/creating-a-python-virtual-environment-for-pyqgis-development-with-vs-code-on-windows.png" type="image/png" length="712997"/>
</item>
```

Investigating, I understand that you scrap the sources to convert feeds item into markdown before genrating a static website right? And you commit the markdown right into this repository, right?

For geotribu english blog, items are duplicated:

- https://github.com/qgis/QGIS-Planet-Website/blob/e7f170d3f122a0f59375ddf5a58c3440e8f90df3/content/posts/creating-a-python-virtual-environment-for-pyqgis-development-with-vs-code-on-windows.png.md
- https://github.com/qgis/QGIS-Planet-Website/blob/e7f170d3f122a0f59375ddf5a58c3440e8f90df3/content/posts/creating-a-python-virtual-environment-for-pyqgis-development-with-vs-code-on-windows.png.png

I suspect that the webscraping is bugguy when it comes to extract the learn more URL and it both use the `link` and the `enclosure` elements, no?

FYI, Geotribu's contents are already Markdown --> HTML: https://github.com/geotribu/english-blog/tree/main/content/posts. I guess many websites are also Markdow based. Maybe it would be more direct to use the source markdown instead of trying to convert output HTML back into Markdown.

**Comment by Guts** [comment]
Hi @Xpirix any news?

**Comment by Xpirix** [comment]
Hi @Guts , Thanks for the reminder.

> Investigating, I understand that you scrap the sources to convert feed items into markdown before generating a static website right? And you commit the markdown right into this repository, right?

Yes, that's right. It's a similar workflow as in the current https://plugins.qgis.org/planet/

> I suspect that the webscraping is bugguy when it comes to extract the learn more URL and it both use the link and the enclosure elements, no?

I've looked at it earlier and it seems to need some reviews. I think it always fetches the last URL, which is, in your case the enclosure URL

> Maybe it would be more direct to use the source markdown instead of trying to convert output HTML back into Markdown.

It would need some considerable changes as the current workflow expects a feed RSS XML as an input, parse the feed and add the hugo frontmatter along with the content as a markdown for each post. But we could add another attribute (is_markdown for example) so, instead of providing an RSS feed xml, we can also directly use a link to the markdown file as input and it will follow another process. In this case, we should ensure that the markdown file includes the needed hugo frontmatter. Either the source provides it, or we add a step to append it.

Also, I apologise for the late reaction. This website has not been deployed yet (only available through GH pages) and we are currently busy working on the migration process on this separated planet website (and others). So, I didn't have a chance to work on the open issues. I will try to look at them as soon as possible.

**Comment by Guts** [comment]
Thanks for your analisis.

> I've looked at it earlier and it seems to need some reviews. I think it always fetches the last URL, which is, in your case the enclosure URL

Ok, got it: https://github.com/qgis/QGIS-Planet-Website/blob/main/fetch_feeds.py#L47. I see you use the feedparser package to parse feeds. You could rely on the enclosures types (https://feedparser.readthedocs.io/en/latest/reference-entry-enclosures.html) to identify content hyperlinks, images, etc. 

Quick sample:

```python
from pprint import pprint

import feedparser

rss_source = "https://blog.geotribu.net/feed_rss_created.xml"

feed_parsed = feedparser.parse(rss_source)

# print feed informations
# feed = feed_parsed.get("feed")
# pprint(feed)

# feed items
for feed_item in feed_parsed.entries:
    pprint(feed_item)

```

Output:


```python
[...]
{'author': 'Julien Moura (dev@ingeoveritas.com)',
 'author_detail': {'email': 'dev@guilhemallaman.net',
                   'name': 'Guilhem Allaman'},
 'authors': [{'email': 'dev@guilhemallaman.net', 'name': 'Guilhem Allaman'},
             {'email': 'dev@ingeoveritas.com', 'name': 'Julien Moura'}],
 'comments': 'https://blog.geotribu.net/2024/10/18/introducing-qchat-a-chat-within-qgis/#__comments',
 'guidislink': False,
 'id': 'https://blog.geotribu.net/2024/10/18/introducing-qchat-a-chat-within-qgis/',
 'link': 'https://blog.geotribu.net/2024/10/18/introducing-qchat-a-chat-within-qgis/?utm_source=rss-feed&utm_medium=RSS&utm_campaign=feed-syndication',
 'links': [{'href': 'https://blog.geotribu.net/2024/10/18/introducing-qchat-a-chat-within-qgis/?utm_source=rss-feed&utm_medium=RSS&utm_campaign=feed-syndication',
            'rel': 'alternate',
            'type': 'text/html'},
           {'href': 'https://blog.geotribu.net/assets/images/social/2024/10/18/introducing-qchat-a-chat-within-qgis.png',
            'length': '729969',
            'rel': 'enclosure',
            'type': 'image/png'}],
 'published': 'Fri, 18 Oct 2024 09:09:00 +0000',
 'published_parsed': time.struct_time(tm_year=2024, tm_mon=10, tm_mday=18, tm_hour=9, tm_min=9, tm_sec=0, tm_wday=4, tm_yday=292, tm_isdst=0),
 'source': {'href': 'https://blog.geotribu.net/feed_rss_created.xml',
            'title': 'Geotribu in English'},
 'summary': "In 2024, it's time to leave Teams and IRC behind to enter a new "
            'era where you can chat directly from QGIS with other GIS fellows. '
            '#GISChat #GISTribe',
 'summary_detail': {'base': 'https://blog.geotribu.net/feed_rss_created.xml',
                    'language': None,
                    'type': 'text/html',
                    'value': "In 2024, it's time to leave Teams and IRC behind "
                             'to enter a new era where you can chat directly '
                             'from QGIS with other GIS fellows. #GISChat '
                             '#GISTribe'},
 'tags': [{'label': None, 'scheme': None, 'term': 'Article'},
          {'label': None, 'scheme': None, 'term': 'GISChat'},
          {'label': None, 'scheme': None, 'term': 'GISTribe'},
          {'label': None, 'scheme': None, 'term': 'QChat'},
          {'label': None, 'scheme': None, 'term': 'QGIS'},
          {'label': None, 'scheme': None, 'term': 'QTribu'}],
 'title': 'Introducing QChat: a chat within QGIS!',
 'title_detail': {'base': 'https://blog.geotribu.net/feed_rss_created.xml',
                  'language': None,
                  'type': 'text/plain',
                  'value': 'Introducing QChat: a chat within QGIS!'}}
```

you can see that the content hyperlink is (or might be) under the `link` attribute and the `rel=enclosure` under the `links` attribute.

> Also, I apologise for the late reaction. This website has not been deployed yet (only available through GH pages) and we are currently busy working on the migration process on this separated planet website (and others). So, I didn't have a chance to work on the open issues. I will try to look at them as soon as possible.

No worries, no hurry. It was on my `tofoollowup` list but if the website is still not deployed nor featured, it's not an issue.

**Comment by Xpirix** [comment]
> you can see that the content hyperlink is (or might be) under the link attribute and the rel=enclosure under the links attribute.

Thank you very much for the hint. I will take that into consideration.

**Comment by Xpirix** [comment]
Hi @Guts 

This should be fixed by #35

**Comment by Guts** [comment]
Nice,, thanks @Xpirix!

**Comment by Guts** [comment]
cc @gounux @igeofr FYI
